backend:
  name: github
  repo: decaporg/decap-website
  squash_merges: true
  open_authoring: true
  branch: main

local_backend: true

site_url: https://www.decapcms.org

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

docs_collection: &docs_collection
  folder: content/docs
  create: true
  summary: '{{weight}} - {{title}}'
  preview_path: 'docs/{{slug}}'
  sortable_fields: ['weight', 'title', 'group']
  fields:
    - label: Section
      name: group
      widget: relation
      collection: settings
      file: docs_sections
      search_fields: ['menu.docs.*.name', 'menu.docs.*.title']
      display_fields: ['menu.docs.*.title']
      value_field: 'menu.docs.*.name'
    - { label: 'Order', name: weight, widget: number }
    - { label: Title, name: title }
    - { label: Body, name: body, widget: markdown }

collections:
  - label: Settings
    name: settings
    hide: true
    files:
      - label: Docs Sections
        name: docs_sections
        file: site.yml
        fields:
          - label: menu
            name: menu
            widget: object
            fields:
              - label: Sections
                label_singular: Section
                name: docs
                widget: list
                summary: '{{title}} ({{name}})'
                fields:
                  - { label: 'Full Name', name: 'title', widget: 'string' }
                  - { label: 'Summary Name', name: 'name', widget: 'string' }

  - <<: *docs_collection
    name: docs_intro
    label: 'Docs: Intro'
    filter:
      field: group
      value: Intro
  - <<: *docs_collection
    name: docs_add_to_site
    label: 'Docs: Add to Site'
    filter:
      field: group
      value: Add
  - <<: *docs_collection
    name: docs_backends
    label: 'Docs: Backends'
    filter:
      field: group
      value: Backends
  - <<: *docs_collection
    name: docs_configuration
    label: 'Docs: Configuration'
    filter:
      field: group
      value: Configuration
  - <<: *docs_collection
    name: docs_media
    label: 'Docs: Media'
    filter:
      field: group
      value: Media
  - <<: *docs_collection
    name: docs_workflow
    label: 'Docs: Workflow'
    filter:
      field: group
      value: Workflow
  - <<: *docs_collection
    name: docs_collections
    label: 'Docs: Collections'
    filter:
      field: group
      value: Collections
  - <<: *docs_collection
    name: docs_fields
    label: 'Docs: Fields'
    filter:
      field: group
      value: Fields
  - <<: *docs_collection
    name: docs_guides
    label: 'Docs: Guides'
    filter:
      field: group
      value: Guides
  - <<: *docs_collection
    name: docs_customization
    label: 'Docs: Customization'
    filter:
      field: group
      value: Customization
  - <<: *docs_collection
    name: docs_contributing
    label: 'Docs: Contributing'
    filter:
      field: group
      value: Contributing
  - name: widget_docs
    label: 'Docs: Widgets'
    folder: content/docs/widgets
    preview_path: 'docs/widgets/{{title}}'
    create: true
    fields:
      - { label: Name, name: title }
      - { label: Label, name: label }
      - { label: Body, name: body, widget: markdown }
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/blog
    preview_path: 'blog/{{year}}/{{month}}/{{title}}'
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Author, name: author }
      - { label: Description (for blog list), name: description, widget: text }
      - {
          label: Meta Description (defaults to Description),
          name: meta_description,
          widget: text,
          required: false,
        }
      - { label: Image, name: image, widget: image }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
  - name: community
    label: Community
    files:
      - name: community
        label: Community
        file: content/pages/community.md
        preview_path: community
        fields:
          - { label: Title, name: title }
          - { label: Headline, name: headline }
          - { label: Subheading, name: subhead }
          - label: Sections
            name: sections
            widget: list
            fields:
              - { name: title, label: Title }
              - name: channels
                label: Channels
                widget: list
                fields:
                  - { name: title, label: Title }
                  - { name: url, label: URL }
                  - { name: description, label: Description }
